server:
  port: 8082

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: picture-sod
#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/picture_sod?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always

#flyway:
#  url: jdbc:mysql://localhost:3307/picture_sod?autoReconnect=true&useSSL=false
#  user: root
#  password: root
#  locations: classpath:/db