DROP TABLE IF EXISTS uploading;
CREATE TABLE `uploading` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `group_id` BIGINT(20),
  `path` VARCHAR(100) NOT NULL,
  `approval_count` INTEGER NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;